version: "3.8"

services:
  chromadb:
    image: chromadb/chroma:1.0.16
    container_name: shard-md-test-chromadb
    ports:
      - "8000:8000"
    environment:
      - ANONYMIZED_TELEMETRY=false
      - ALLOW_RESET=true
      - CHROMA_SERVER_NOFILE=65536
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:8000/api/v2/heartbeat || curl -f http://localhost:8000/api/v1/heartbeat || curl -f http://localhost:8000/heartbeat || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - chromadb_data:/chroma/chroma
    networks:
      - shard_md_test

volumes:
  chromadb_data:

networks:
  shard_md_test:
    driver: bridge
