"""Test constants to replace magic numbers."""

# Default test configurations
DEFAULT_CHUNK_SIZE = 1000
DEFAULT_OVERLAP = 200
DEFAULT_PORT = 8000
DEFAULT_HOST = "localhost"

# Test data sizes
SMALL_CONTENT_SIZE = 300
MEDIUM_CONTENT_SIZE = 800
LARGE_CONTENT_SIZE = 1500
VERY_LARGE_CONTENT_SIZE = 1000000

# Test limits and thresholds
MAX_COLLECTION_NAME_LENGTH = 255
QUERY_RESULT_LIMIT = 10
BATCH_SIZE_LIMIT = 15
PERFORMANCE_TEST_ITERATIONS = 50
LARGE_DATASET_ITERATIONS = 100

# Test timeouts (in seconds)
CONNECTION_TIMEOUT = 60
PROCESSING_TIMEOUT = 60

# Test file counts
SMALL_FILE_COUNT = 20
LARGE_FILE_COUNT = 50

# Test repetition factors
CONTENT_REPEAT_FACTOR = 10
PERFORMANCE_REPEAT_FACTOR = 20
LARGE_CONTENT_REPEAT_FACTOR = 50

# Test ages (for sample data)
SAMPLE_AGE_ALICE = 30
SAMPLE_AGE_BOB = 25
SAMPLE_AGE_CHARLIE = 35

# Test dates
TEST_YEAR = 2024
TEST_MONTH = 1
TEST_DAY = 1
TEST_DATE_STRING = "2024-01-01"

# Position constants
START_POSITION_FIRST = 0
START_POSITION_SECOND = 31
START_POSITION_THIRD = 61
END_POSITION_FIRST = 30
END_POSITION_SECOND = 60
END_POSITION_THIRD = 90

# Metadata constants
SAMPLE_WORD_COUNT = 50
SAMPLE_READING_TIME = 1

# Performance test parameters
PERFORMANCE_CONTENT_SIZE = 400
PERFORMANCE_CONTENT_DIVISOR = 34  # For calculating repeat factor
